[package]
name = "expand_str"
version = "0.1.0"
authors = ["TechPriest <yaminogakusei@gmail.com>"]
edition = "2018"
license = "WTFPL"
keywords = ["string", "formatting", "ExpandEnvironmentStrings"]


[features]
default = ["env"]
env = []

[dependencies]
